// leave off @2x/@3x
const Images = {
    launch: require('../Images/default.png'),
    loginScreenBase: require('../Images/login-screen-base.png'),
    logoImage: require('../Images/logo.png'),
	homeIcon: require('../Images/Dashboard/logo.png'),
    costFirstText: require('../Images/cost-first-text.png'),
    username: require('../Images/username-icon.png'),
    password: require('../Images/password-icon.png'),
    unselectedCheckbox: require('../Images/unselected-checkbox.png'),
    emailid: require('../Images/email-id.png'),
    nextarrow: require('../Images/next-arrow.png'),
    previousarrow: require('../Images/previous-arrow.png'),
    mailing_address_icon: require('../Images/mailing-address-icon.png'),
    location_icon: require('../Images/location-icon.png'),
    zip_code_icon: require('../Images/zip-code-icon.png'),
	rent_vs_buyer: require('../Images/rent_vs_buyer.png'),
	graph: require('../Images/graph.png'),
    phone_number_icon: require('../Images/phone-number-icon.png'),
    back_icon: require('../Images/back-icon.png'),
    header_background: require('../Images/header-base.png'),
    address_icon:  require('../Images/address-icon.png'),
    upload_icon:  require('../Images/upload-icon.png'),
    user_icon:  require('../Images/user-icon.png'),
	buyer:  require('../Images/buyer.png'),
	buyer_highlight:  require('../Images/buyer-highlight.png'),
	closing_cost:  require('../Images/closing-cost.png'),
	closing_cost_highlight:  require('../Images/closing-cost-highlight.png'),
	prepaid:  require('../Images/prepaid.png'),
	prepaid_highlight:  require('../Images/prepaid-highlight.png'),
	payment:  require('../Images/payment.png'),
	payment_highlight:  require('../Images/payment-highlight.png'),
	buyer_closing_white_icon:  require('../Images/buyer-closing-cost-selected-icon.png'),
	buyer_closing_icon:  require('../Images/buyer-closing-cost-unselected-icon.png'),
	seller_closing_icon:  require('../Images/seller-closing-cost-unselected-icon.png'),
	multiple_offer_icon:  require('../Images/Dashboard/multi_offer.png'),
	refinance_closing_icon:  require('../Images/refinance-closing-cost-unselected-icon.png'),
	quick_notes_icon:  require('../Images/Quick-Quotes-unselected-icon.png'),
	address_book_icon:  require('../Images/address-book-unselected-icon.png'),
	app_setting_icon:  require('../Images/settings-unselected-icon.png'),
	my_account_icon:  require('../Images/my-account-unselected-icon.png'),
	my_title_rep_icon:  require('../Images/My-title-rep-unselected-icon.png'),
	speak_text_icon:  require('../Images/speak-to-text-selected-switch.png'),
	speak_text_icon_unselected:  require('../Images/speak-to-text-unselected-switch.png'),
	net_first_icon:  require('../Images/net-first-unselected-icon.png'),
	refinance:  require('../Images/refinance.png'),
	refinance_highlight:  require('../Images/refinance-highlight.png'),
	change_country_state_icon:  require('../Images/change-state-&-country-unselected-icon.png'),
	privacy_policy_icon:  require('../Images/privace-policy-unselected-icon.png'),
	recycle:  require('../Images/recycle.png'),
	pdf:  require('../Images/pdf-sample.pdf'),
	video_camera:  require('../Images/video_camera.png'),
	message:  require('../Images/message.png'),
	camera:  require('../Images/camera.png'),
	seller_selected: require('../Images/seller_selected.png'),
	seller_unselected: require('../Images/seller_unselected.png'),
    other_costs_selected: require('../Images/other_costs_selected.png'),
    other_costs_unselected: require('../Images/other_costs_unselected.png'),
    dropdown_arrow: require('../Images/dropdown-arrow.png'),
    unselected_checkbox: require('../Images/unselected-checkbox.png'),
    selected_checkbox: require('../Images/selected-checkbox.png'),
    text_icon: require('../Images/text-icon.png'),
    eagle: require('../Images/Eagle.png'),
	play: require('../Images/play.png'),
	pause: require('../Images/pause.png'),
	logout: require('../Images/logout.png'),
	micIcon: require('../Images/mic-icon.png'),
	evernoteIcon: require('../Images/evernote.png'),
	dropboxIcon: require('../Images/dropbox.png'),
	googledriveIcon: require('../Images/google-drive.png'),
	internetConnectionOffIcon: require('../Images/error.png'),
	
	
}

export default Images
