module.exports = {
  BASE_URL: 'http://demoadmin.costsfirst.com/',
  GOOGLE_PLACE_API_KEY : 'AIzaSyAkg1ayUfOxduZLATIwb2_wdqJNn1Y1vHo',
  Login_Api: 'auth-login',
  Check_Username: 'api/check-username',
  Get_States:'api/get-states',
  Get_County: 'api/get-county',
  Get_County_id : 'api/get-county-id',
  Verify_ZipCode: 'api/verify-zipcode',
  Get_City_County_State: 'api/get-city-county-state',
  Get_Title_Rep: 'api/get-title-rep',
  Save_User: 'api/save-user',
  Forgot_Username: 'forgot-username',
  Forgot_Password: 'forgot-password',
  User_Detail: 'api/user-detail',
  Update_User: 'api/update-user',
  buyer_escrow_xml_data: 'api/buyer-escrow-xml-data',
  refinance_escrow_xml_data: 'api/refinance-escrow-xml-data',
  fha_va_usda_setting_api: 'api/fha-va-usda-setting',
  update_fha_va_usda_setting_api : 'api/update-fha-va-usda-user-setting',
  state_buyer_proration_global_setting: 'api/state-buyer-impound-global-setting',
  national_global_setting: 'api/national-global-setting',
  getMultipleOffer : 'api/getoffer',
  multipleOfferPdf : 'api/multipleofferpdf/en',
  save_buyer_calculator: 'api/save-buyer-calculator',
  Change_Password : 'api/change-password',
  save_seller_calculator: 'api/save-seller-calculator',
  netfirst_seller_calculator: 'api/save-netfirst-calculator',
  Delete_Refinance_Calculator : 'api/delete-refinance-calculator',
  Delete_Buyer_Calculator : 'api/delete-buyer-calculator',
  Delete_Seller_Calculator : 'api/delete-seller-calculator',
  Delete_NetFirst_Calculator : 'api/delete-netfirst-calculator',
  get_buyer_calculator: 'api/get-buyer-calculator',
  get_seller_calculator: 'api/get-seller-calculator',
  get_netfirst_calculator: 'api/get-netfirst-calculator',
  buyer_detail_calculator: 'api/buyer-detail-calculator',
  seller_detail_calculator: 'api/seller-detail-calculator',
  netfirst_detail_calculator: 'api/netfirst-detail-calculator',
  generate_pdf: 'api/generate-pdf',
  generate_pdf_quick_buyer: 'api/generate-pdf-quick-buyer',
  generate_pdf_quick_seller: 'api/seller-quick-pdf',
  generate_pdf_detail_seller: 'api/seller-detail-pdf',
  generate_pdf_owner_carry: 'api/ownercarry',


  generate_pdf_quick_netfirst: 'api/netfirst-quick-pdf',
  generate_pdf_detail_netfirst: 'api/netfirst-detail-pdf',
  user_address_book: 'api/list-address-book',
  send_buyer_detailed_estimate: 'api/send-buyer-detailed-estimate',
  seller_escrow_xml_data: 'api/seller-escrow-xml-data',
  seller_escrow_type: 'api/title-escrow-type',
  netfirst_escrow_type: 'api/title-escrow-type',
  Seller_Cost_Setting: 'api/seller-cost-setting',
  NetFirst_Cost_Setting: 'api/seller-cost-setting',
  Update_Seller_Cost_Setting: 'api/update-seller-cost-setting',
  fha_va_usda_common_setting: 'api/fha-va-usda-common-setting',
  refinance_setting: 'api/refinance-cost-setting',
  seller_proration_setting: 'api/seller-proration-setting',
  update_fha_va_usda_common_setting: 'api/update-fha-va-usda-user-setting',
  refinance_setting: 'api/refinance-cost-setting',
  Update_refinance_setting: 'api/update-refinance-cost-setting',
  Buyer_Cost_Setting: 'api/buyer-cost-setting',
  Update_Buyer_Cost_Setting: 'api/update-buyer-cost-setting',
  conventional_setting: 'api/conventional-setting',
  Update_conventional_setting: 'api/update-conventional-cost-setting',
  TRID_CDTC_Setting: 'api/list-cdtc-trid-setting',
  Update_TRID_CDTC: 'api/update-cdtc-trid-setting',
  Update_Load_Comparison: 'api/update-loan-comparison-setting',
  Update_Other_Escrow: 'api/update-other-escrow-setting',
  Upload_Image_Email : 'api/upload-image-email',
  Upload_Video_Email_Mobile : 'api/upload-video-email',
  Rent_vs_Buy_Email_Print_Api : 'api/rent-vs-buy-print',
  commission_setting: 'api/list-user-commission-setting',
  Update_commission_setting: 'api/update-user-commission-setting',
  Save_contact_addressBook: 'api/save-address-book',
  Update_contact_addressBook: 'api/update-address-book',
  Delete_contact_addressBook: 'api/delete-address-book',
  Refinance_Cost_Setting: 'api/refinance-cost-setting',
  Get_Refinance_Calculator: 'api/get-refinance-calculator',
  detail_refinance_calculator: 'api/detail-refinance-calculator',
  save_refinance_calculator: 'api/save-refinance-calculator',
  refinance_detail_pdf: 'api/refinance-detail-pdf',
  title_escrow_type: 'api/title-escrow-type',
  refinance_escrow_xml_data: 'api/refinance-escrow-xml-data',
  get_transfer_tax: 'api/get-transfer-tax',
  ca_transfer_tax: 'api/ca-transfer-tax',
  get_city_state_for_zip: 'api/get-city-state-for-zip',
  reload_user_setting: 'api/reload-user-setting',
  buyer_proration_setting: 'api/buyer-proration-setting',
  quick_quotes_get_refi_data : 'api/get-refi-data',
  quick_quotes_get_sale_data : 'api/get-sale-data',
  Get_Quick_Qoute_Pdf : 'api/get-quick-qoute-pdf',
  update_cdtc_trid_setting: 'api/update-cdtc-trid-setting',
  buyer_cdtc_pdf : 'api/getcdtc',
  buyer_trid_pdf : 'api/gettrid',
  seller_send_text_message_api : 'api/textmessage',
  refinance_trid_pdf : 'api/get-refi-trid',
  refinance_cdtc_pdf :  'api/get-refi-cdtc',
  loan_comparison_pdf: 'api/loan-comparison-pdf',
  ssomobile: 'api/ssomobile',
  registerSingleSignOn: 'api/register-singlesignon',
  county_global_setting : 'api/county-global-setting',
  notify_for_setting_update : 'api/notify-for-setting-update',
  calcownercarry : 'api/calcownercarry',
  title_rep_details: 'http://www.firstphoneapps.com/webservice/titlerepdetails/repid/'
};
